#!/usr/bin/env python3
"""Build porter_routh_feed.xml from data/porter_routh_oral_history.csv."""

from pathlib import Path

from feedlib import FeedConfig, write_feed

CONFIG = FeedConfig(
    csv_path=Path("data/porter_routh_oral_history.csv"),
    out_path=Path("porter_routh_feed.xml"),
    title="SBHLA Porter Routh Oral History (Personal Archive)",
    link="https://sbhla.org/digital-resources/sbc-leaders-oral-history/routh-porter-wroe-oral-history/",
    description=(
        "Personal listening feed for the 1986-1987 oral history interview with "
        "Porter Routh, longtime Executive Secretary-Treasurer of the SBC "
        "Executive Committee, conducted by A. Ronald Tonks. Recordings preserved "
        "and hosted by the Southern Baptist Historical Library & Archives. Not "
        "affiliated with or endorsed by SBHLA; for personal use only."
    ),
    category="Society &amp; Culture",
    # porter_routh_artwork.jpg is generated by artwork/make_artwork.py.
    image="https://laholmes2.github.io/sbhla-podcast/porter_routh_artwork.jpg",
)

if __name__ == "__main__":
    write_feed(CONFIG)
