#!/usr/bin/env python3
"""Build louie_newton_feed.xml from data/louie_newton.csv."""

from pathlib import Path

from feedlib import FeedConfig, write_feed

CONFIG = FeedConfig(
    csv_path=Path("data/louie_newton.csv"),
    out_path=Path("louie_newton_feed.xml"),
    title="SBHLA Louie D. Newton Sermons (Personal Archive)",
    link="https://sbhla.org/digital-resources/louie-d-newton-sermons-audio-recordings/",
    description=(
        "Personal listening feed for sermons by Louie D. Newton, longtime pastor "
        "of Druid Hills Baptist Church, Atlanta, GA, preserved and hosted by the "
        "Southern Baptist Historical Library & Archives. Not affiliated with or "
        "endorsed by SBHLA; for personal use only."
    ),
    # louie_newton_artwork.jpg is generated by artwork/make_artwork.py.
    image="https://laholmes2.github.io/sbhla-podcast/louie_newton_artwork.jpg",
)

if __name__ == "__main__":
    write_feed(CONFIG)
