#!/usr/bin/env python3
"""Build baptist_hour_feed.xml from data/baptist_hour_1945.csv."""

from pathlib import Path

from feedlib import FeedConfig, write_feed

CONFIG = FeedConfig(
    csv_path=Path("data/baptist_hour_1945.csv"),
    out_path=Path("baptist_hour_feed.xml"),
    title="SBHLA Baptist Hour Recordings (Personal Archive)",
    link="https://sbhla.org/digital-resources/baptist-hour-audio-recordings/",
    description=(
        "Personal listening feed for Baptist Hour radio broadcast recordings "
        "preserved and hosted by the Southern Baptist Historical Library & "
        "Archives. Not affiliated with or endorsed by SBHLA; for personal use only."
    ),
    # baptist_hour_artwork.jpg is generated by artwork/make_artwork.py.
    image="https://laholmes2.github.io/sbhla-podcast/baptist_hour_artwork.jpg",
)

if __name__ == "__main__":
    write_feed(CONFIG)
