#!/usr/bin/env python3
"""Build feed.xml (Pastor's Conference show) from data/sermons.csv."""

from pathlib import Path

from feedlib import FeedConfig, write_feed

CONFIG = FeedConfig(
    csv_path=Path("data/sermons.csv"),
    out_path=Path("feed.xml"),
    title="SBHLA Pastor's Conference Recordings (Personal Archive)",
    link="https://sbhla.org/digital-resources/pastors-conference-audio-recordings/",
    description=(
        "Personal listening feed for audio recordings preserved and hosted by the "
        "Southern Baptist Historical Library & Archives. Not affiliated with or "
        "endorsed by SBHLA; for personal use only."
    ),
    # artwork.jpg is generated by artwork/make_artwork.py.
    image="https://laholmes2.github.io/sbhla-podcast/artwork.jpg",
)

if __name__ == "__main__":
    write_feed(CONFIG)
