#!/usr/bin/env python3
"""Build feed.xml (a podcast RSS feed) from data/sermons.csv."""

import csv
import html
from datetime import datetime, timezone
from pathlib import Path

CSV_PATH = Path("data/sermons.csv")
OUT_PATH = Path("feed.xml")

FEED_TITLE = "SBHLA Pastor's Conference Recordings (Personal Archive)"
FEED_LINK = "https://sbhla.org/digital-resources/pastors-conference-audio-recordings/"
FEED_DESCRIPTION = (
    "Personal listening feed for audio recordings preserved and hosted by the "
    "Southern Baptist Historical Library & Archives. Not affiliated with or "
    "endorsed by SBHLA; for personal use only."
)
FEED_AUTHOR = "Southern Baptist Historical Library & Archives"
FEED_LANGUAGE = "en-us"
# artwork.jpg is generated by artwork/make_artwork.py. Podcast apps need an
# absolute URL, so update this once feed.xml (and artwork.jpg alongside it)
# are actually hosted somewhere (e.g. GitHub Pages).
FEED_IMAGE = "REPLACE_WITH_HOSTED_ARTWORK_URL/artwork.jpg"


def esc(s: str) -> str:
    return html.escape(s, quote=True)


def parse_duration_to_seconds(duration: str) -> int:
    parts = [int(p) for p in duration.split(":")]
    seconds = 0
    for p in parts:
        seconds = seconds * 60 + p
    return seconds


def rfc822(date_str: str) -> str:
    dt = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    return dt.strftime("%a, %d %b %Y %H:%M:%S %z")


def build_item(row: dict) -> str:
    title = esc(row["title"])
    full_description = row["description"] + f" Full printed program: {row['program_pdf']}"
    description = esc(full_description)
    mp3_url = esc(row["mp3_url"])
    length = row["bytes"]
    pub_date = rfc822(row["date"])
    duration_seconds = parse_duration_to_seconds(row["duration"])
    guid = esc(row["mp3_url"])
    source_page = esc(row["source_page"])

    return f"""    <item>
      <title>{title}</title>
      <description>{description}</description>
      <link>{source_page}</link>
      <enclosure url="{mp3_url}" length="{length}" type="audio/mpeg"/>
      <guid isPermaLink="false">{guid}</guid>
      <pubDate>{pub_date}</pubDate>
      <itunes:duration>{duration_seconds}</itunes:duration>
      <itunes:explicit>false</itunes:explicit>
    </item>"""


def build_feed(rows: list[dict]) -> str:
    items = "\n".join(build_item(row) for row in rows)
    last_build = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S %z")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>{esc(FEED_TITLE)}</title>
    <link>{esc(FEED_LINK)}</link>
    <description>{esc(FEED_DESCRIPTION)}</description>
    <language>{FEED_LANGUAGE}</language>
    <lastBuildDate>{last_build}</lastBuildDate>
    <itunes:author>{esc(FEED_AUTHOR)}</itunes:author>
    <itunes:explicit>false</itunes:explicit>
    <itunes:category text="Religion &amp; Spirituality"/>
    <itunes:image href="{esc(FEED_IMAGE)}"/>
    <image>
      <url>{esc(FEED_IMAGE)}</url>
      <title>{esc(FEED_TITLE)}</title>
      <link>{esc(FEED_LINK)}</link>
    </image>
{items}
  </channel>
</rss>
"""


def main() -> None:
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    feed_xml = build_feed(rows)
    OUT_PATH.write_text(feed_xml, encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(rows)} episodes")
    if "REPLACE_WITH_HOSTED_ARTWORK_URL" in FEED_IMAGE:
        print(
            "WARNING: FEED_IMAGE is still a placeholder. Update it in build_feed.py "
            "to the real hosted URL of artwork.jpg once this feed is published."
        )


if __name__ == "__main__":
    main()
